package sermk.pipi.pilib;

/**
 * Created by echormonov on 10.01.18.
 */

public class CommandCollection {
    public static final String ACTION_RECIVER_PILAUNCHER_SET_SETTINGS = "ACTION_RECIVER_PILAUNCHER_SET_SETTINGS";
    public static final String ACTION_RECIVER_PILAUNCHER_SAVE_SETTINGS = "ACTION_RECIVER_PILAUNCHER_SAVE_SETTINGS";
    public static final String ACTION_RECIVER_INSTALL_PACKAGE = "INSTALL_PACKAGE";
    public static final String ACTION_RECIVER_REMOVE_PACKAGE = "REMOVE_PACKAGE";

    public static final String ACTION_RECIVER_DPC_SET_SETTINGS = "ACTION_RECIVER_DPC_SET_SETTINGS";
    public static final String ACTION_RECIVER_DPC_SAVE_SETTINGS = "ACTION_RECIVER_DPC_SAVE_SETTINGS";

    public static final String ACTION_RECIVER_SET_PI_STATUS ="SET_PI_STATUS";
    public static final String ACTION_RECIVER_CLEAR_CAPTURE_FRAME_INTERVAL ="ACTION_RECIVER_CLEAR_CAPTURE_FRAME_INTERVAL";

    public static final String ACTION_RECIVER_PIBALL_SET_AND_SAVE_SETTINGS ="ACTION_RECIVER_PIBALL_SET_AND_SAVE_SETTINGS";

    public static final String ACTION_RECIVER_FOR_ALL_QUERY_SETTINGS ="ACTION_RECIVER_FOR_ALL_QUERY_SETTINGS";
    public static final String ACTION_RECIVER_MCLIENT_SET_AND_SAVE_SETTINGS ="ACTION_RECIVER_MCLIENT_SET_AND_SAVE_SETTINGS";

    public static final String ACTION_RECIEVER_MCLIENT_CONNECTION_RESULT = "ACTION_RECIEVER_MCLIENT_CONNECTION_RESULT";

}
